import { Context } from '@/AvtaleProvider';
import { Formidlingsgruppe } from '@/AvtaleSide/steg/BeregningTilskudd/Formidlingsgruppe';
import { Kvalifiseringsgruppe } from '@/AvtaleSide/steg/BeregningTilskudd/Kvalifiseringsgruppe';
import { Returårsaker, Avtale } from '@/types/avtale';
import { Avtaleinnhold } from './../types/avtale';

const avtaleInnhold: Avtale | Avtaleinnhold = {
    arbeidsgiverEtternavn: '',
    arbeidsgiverFornavn: '',
    arbeidsgiverKontonummer: '',
    arbeidsgiverTlf: '',
    arbeidsgiveravgift: 1,
    arbeidsgiveravgiftBelop: 100,
    bedriftNavn: '',
    deltakerEtternavn: '',
    deltakerFornavn: '',
    deltakerTlf: '',
    feriepengerBelop: 1,
    feriepengesats: 100,
    harFamilietilknytning: false,
    kvalifiseringsgruppe: Kvalifiseringsgruppe.SPESIELT_TILPASSET_INNSATS,
    formidlingsgruppe: Formidlingsgruppe.ARBEIDSSOKER,
    maal: [{ beskrivelse: '', kategori: 'ANNET', id: '' }],
    mentorAntallTimer: 1,
    mentorEtternavn: '',
    mentorFornavn: '',
    mentorOppgaver: '',
    mentorTimelonn: 1,
    oppfolging: '',
    otpBelop: 1,
    sluttDato: '',
    startDato: '',
    stillingprosent: 1,
    sumLonnstilskudd: 1,
    sumLonnsutgifter: 111,
    tilskuddPeriode: [
        {
            løpenummer: 1,
            beløp: 10000,
            id: '123123',
            startDato: '',
            sluttDato: '',
            godkjentTidspunkt: '',
            status: 'UBEHANDLET',
            avslagsårsaker: new Set<Returårsaker>(),
            lonnstilskuddProsent: 60,
            kanBesluttesFom: '2021-01-01',
            kanBehandles: true,
            aktiv: true,
        },
    ],
    tilrettelegging: '',
    veilederEtternavn: '',
    veilederFornavn: '',
    veilederTlf: '',
    bedriftNr: '',
    deltakerFnr: '',
    erUfordelt: false,
    godkjentAvArbeidsgiver: '',
    godkjentAvDeltaker: '',
    godkjentAvVeileder: '',
    godkjentPaVegneAv: false,
    id: '',
    opprettetTidspunkt: '',
    sistEndret: '',
    tiltakstype: 'ARBEIDSTRENING',
    veilederNavIdent: '',
    beslutterNavIdent: '',
    status: 'GJENNOMFØRES',
    felterSomIkkeErFyltUt: [],
    avtaleNr: 1,
    godkjentForEtterregistrering: false,
    inkluderingstilskuddsutgift: [],
    inkluderingstilskuddBegrunnelse: '',
    inkluderingstilskuddTotalBeløp: 0,
    inkluderingstilskuddSats: 149_100,
    innholdType: 'INNGÅ',
};

export const contextMock: Partial<Context> = {
    //avtale: avtaleInnhold,
    settOgKalkulerBeregningsverdier: () => Promise.resolve(),
    settAvtaleInnholdVerdi: () => null,
    settAvtaleInnholdVerdier: () => undefined,
    hentAvtale: () => Promise.resolve(),
    annullerAvtale: () => Promise.resolve(),
    lagreAvtale: () => Promise.resolve(),
    overtaAvtale: () => Promise.resolve(),
    utforHandlingHvisRedigerbar: () => Promise.resolve(),
    lagreMaal: () => Promise.resolve(),
    slettMaal: () => Promise.resolve(),
    endretSteg: () => Promise.resolve(),
    godkjenn: () => Promise.resolve(),
    godkjennTilskudd: () => Promise.resolve(),
    returnerTilskuddsperiode: () => Promise.resolve(),
    godkjennPaVegneAvDeltaker: () => Promise.resolve(),
    godkjennPaVegneAvArbeidsgiver: () => Promise.resolve(),
    godkjennPaVegneAvDeltakerOgArbeidsgiver: () => Promise.resolve(),
    ulagredeEndringer: false,
    mellomLagring: undefined,
    setMellomLagring: () => null,
    sendTilbakeTilBeslutter: () => Promise.resolve(),
};
