import { Context } from '@/AvtaleProvider';
import { AltAvtaleinnhold, Avtale } from '@/types/avtale';

const altAvtaleInnhold: Avtale<AltAvtaleinnhold> = {
    arbeidsgiverEtternavn: '',
    arbeidsgiverFornavn: '',
    arbeidsgiverKontonummer: '',
    arbeidsgiverTlf: '',
    arbeidsgiveravgift: 1,
    arbeidsgiveravgiftBelop: 100,
    bedriftNavn: '',
    deltakerEtternavn: '',
    deltakerFornavn: '',
    deltakerTlf: '',
    feriepengerBelop: 1,
    feriepengesats: 100,
    harFamilietilknytning: false,
    maal: [{ beskrivelse: '', kategori: 'ANNET', id: '' }],
    mentorAntallTimer: 1,
    mentorEtternavn: '',
    mentorFornavn: '',
    mentorOppgaver: '',
    mentorTimelonn: 1,
    oppfolging: '',
    otpBelop: 1,
    sluttDato: '',
    startDato: '',
    stillingprosent: 1,
    sumLonnstilskudd: 1,
    sumLonnsutgifter: 111,
    tilrettelegging: '',
    veilederEtternavn: '',
    veilederFornavn: '',
    veilederTlf: '',
    avbrutt: false,
    avbruttDato: '',
    avbruttGrunn: '',
    bedriftNr: '',
    deltakerFnr: '',
    erLaast: false,
    erUfordelt: false,
    godkjentAvArbeidsgiver: false,
    godkjentAvDeltaker: false,
    godkjentAvVeileder: false,
    godkjentPaVegneAv: false,
    id: '',
    kanAvbrytes: true,
    kanGjenopprettes: false,
    kanLåsesOpp: false,
    opprettetTidspunkt: '',
    sistEndret: '',
    status: '',
    tiltakstype: 'ARBEIDSTRENING',
    veilederNavIdent: '',
    versjoner: [],
};

export const contextMock: Context = {
    avtale: altAvtaleInnhold,
    settAvtaleVerdi: () => null,
    hentAvtale: () => Promise.resolve(),
    avbrytAvtale: () => Promise.resolve(),
    lagreAvtale: () => Promise.resolve(),
    overtaAvtale: () => Promise.resolve(),
    laasOpp: () => Promise.resolve(),
    gjenopprettAvtale: () => Promise.resolve(),
    utforHandlingHvisRedigerbar: () => Promise.resolve(),
    lagreMaal: () => Promise.resolve(),
    slettMaal: () => Promise.resolve(),
    endretSteg: () => Promise.resolve(),
    godkjenn: () => Promise.resolve(),
    godkjennPaVegne: () => Promise.resolve(),
    ulagredeEndringer: false,
    mellomLagring: undefined,
    setMellomLagring: () => null,
};
