FROM node:alpine as builder
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM navikt/node-express:12.2.0-alpine as runner
RUN npm install -g helmet
RUN npm install -g http-proxy-middleware
WORKDIR /app
COPY --from=builder build ./build
COPY . .
EXPOSE 3000

