version: '3'
services:
    frontend:
        build: .
        ports:
            - 3090:3000
        environment:
            - API_URL=http://host.docker.internal:8080
            - LOGOUT_URL=http://localhost:3000
