apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: tiltaksgjennomforing
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    image: {{image}}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: {{vault-enabled}}
    ingresses:
        - '{{{ingress}}}'
    liveness:
        path: /tiltaksgjennomforing/internal/isAlive
        initialDelay: 5
    readiness:
        path: /tiltaksgjennomforing/internal/isReady
        initialDelay: 5
    env:
        - name: APIGW_URL
          value: '{{{api-gw-url}}}'
        - name: ISSO_LOGIN_URL
          value: '{{{isso-login-url}}}'
        - name: SELVBETJENING_LOGIN_URL
          value: '{{{selvbetjening-login-url}}}'
        - name: LOGOUT_URL
          value: '{{{logout-url}}}'
        - name: ENABLE_EXTERNAL_MENU
          value: '{{{enable-external-menu}}}'
        - name: DECORATOR_EXTERNAL_URL
          value: '{{{decorator-external-url}}}'
