import VeilederAvtaleStatus from '@/AvtaleSide/AvtaleStatus/VeilederAvtaleStatus';
import { http, HttpResponse } from 'msw';
import { Meta, StoryObj } from '@storybook/react-vite';

import { Avtale, AvtaleStatus } from '@/types/avtale';
import lonnstilskuddAvtaleMock from '@/mocking/lonnstilskudd-avtale-mock';

const meta = {
    title: 'Tiltaksgjennomforing/Statuser/Veileder',
    component: VeilederAvtaleStatus,
    parameters: {
        // More on how to position stories at: https://storybook.js.org/docs/configure/story-layout
        layout: 'fullscreen',
    },
} satisfies Meta<typeof VeilederAvtaleStatus>;

export default meta;
type Story = StoryObj<typeof meta>;

const kreverAktsomhetHandler = [
    http.get('/tiltaksgjennomforing/api/avtaler/1/krever-aktsomhet', () => {
        return HttpResponse.json({ kreverAktsomhet: false });
    }),
    http.get('/tiltaksgjennomforing/api/avtaler/6/krever-aktsomhet', () => {
        return HttpResponse.json({ kreverAktsomhet: true });
    }),
];

const erUfordelt: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: true,
    status: 'ANNULLERT',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ErUfordelt: Story = {
    name: 'Er ufordelt',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: erUfordelt },
};

const annullert: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'ANNULLERT',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const Annullert: Story = {
    name: 'Annullert',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: annullert },
};

const avbrutt: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'AVBRUTT' as AvtaleStatus,
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const Avbrutt: Story = {
    name: 'Avbrutt',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: avbrutt },
};

const påbegynt: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'PÅBEGYNT',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const Påbegynt: Story = {
    name: 'Påbegynt',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: påbegynt },
};

export const PåbegyntKode6: Story = {
    name: 'Påbegynt - kode 6',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: { ...påbegynt, id: '6' } },
};

const manglerGodkjenningVeilederHarGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningVeilederHarGodkjent: Story = {
    name: 'Mangler Godkjenning Veileder har godkjent men manger godkjenning av Beslutter',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningVeilederHarGodkjent },
};

const manglerGodkjenningArbeidsgiverOgDeltakerHarGodkjentMenIkkeMentor: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MENTOR',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2024-05-10',
    godkjentAvArbeidsgiver: '2024-05-10',
    godkjentAvVeileder: '',
    erGodkjentTaushetserklæringAvMentor: false,
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningArbeidsgiverOgDeltakerHarGodkjentMenIkkeMentor: Story = {
    name: 'Mangler Godkjenning Arbeidsgiver og Deltaker har godkjent men manger signering fra Mentor',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningArbeidsgiverOgDeltakerHarGodkjentMenIkkeMentor },
};

const manglerGodkjenningDeltakerOgArbeidsgiverOgMentorHarGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '',
    erGodkjentTaushetserklæringAvMentor: true,
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningDeltakerOgArbeidsgiverOgMentorHarGodkjent: Story = {
    name: ' Mangler Godkjenning Deltaker og Arbeidsgiver og Mentor har godkjent avtalen',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningDeltakerOgArbeidsgiverOgMentorHarGodkjent },
};

const manglerGodkjenningDeltakerHarGodkjentMenIkkeArbeidsgiverOgMentor: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MENTOR',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '',
    godkjentAvVeileder: '',
    erGodkjentTaushetserklæringAvMentor: false,
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningDeltakerHarGodkjentMenIkkeArbeidsgiverOgMentor: Story = {
    name: ' Mangler Godkjenning Deltaker og Arbeidsgiver og Mentor har godkjent avtalen',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningDeltakerHarGodkjentMenIkkeArbeidsgiverOgMentor },
};

const manglerGodkjenningDeltakerHarGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '',
    godkjentAvVeileder: '',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningDeltakerHarGodkjent: Story = {
    name: 'Mangler Godkjenning Deltaker har godkjent men manger godkjenning av Arbeidsgiver',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningDeltakerHarGodkjent },
};

const manglerGodkjenningArbeidsgiverHarGodkjentMenIkkeDeltakerogMentor: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MENTOR',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '',
    godkjentAvArbeidsgiver: '2021-08-01',
    godkjentAvVeileder: '',
    erGodkjentTaushetserklæringAvMentor: false,
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningArbeidsgiverHarGodkjentMenIkkeDeltakerogMentor: Story = {
    name: ' Mangler Godkjenning Deltaker og Arbeidsgiver og Mentor har godkjent avtalen',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningArbeidsgiverHarGodkjentMenIkkeDeltakerogMentor },
};

const manglerGodkjenningArbeidsgiverHarGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '',
    godkjentAvArbeidsgiver: '2024-05-10',
    godkjentAvVeileder: '',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningArbeidsgiverHarGodkjent: Story = {
    name: 'Mangler Godkjenning Arbeidsgiver har godkjent men manger godkjenning av Deltakeren',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningArbeidsgiverHarGodkjent },
};

const manglerGodkjenningArbeidsgiverOgDeltakerOgMentorHarIkkeGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MENTOR',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '',
    godkjentAvArbeidsgiver: '',
    godkjentAvVeileder: '',
    erGodkjentTaushetserklæringAvMentor: false,
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningArbeidsgiverOgDeltakerOgMentorHarIkkeGodkjent: Story = {
    name: 'Mangler Godkjenning Arbeidsgiver har godkjent men manger godkjenning av Deltakeren og Veileder',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningArbeidsgiverOgDeltakerOgMentorHarIkkeGodkjent },
};

const manglerGodkjenningArbeidsgiverOgDeltakerHarIkkeGodkjent: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'MANGLER_GODKJENNING',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '',
    godkjentAvArbeidsgiver: '',
    godkjentAvVeileder: '',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const ManglerGodkjenningArbeidsgiverOgDeltakerHarIkkeGodkjent: Story = {
    name: 'Mangler Godkjenning Arbeidsgiver har godkjent men manger godkjenning av Deltakeren og Veileder',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: manglerGodkjenningArbeidsgiverOgDeltakerHarIkkeGodkjent },
};

const klarForOppstartUteforArena: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'KLAR_FOR_OPPSTART',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const KlarForOppstartUteforArena: Story = {
    name: 'Klar For Oppstart',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: klarForOppstartUteforArena },
};

const klarForOppstartArena: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'KLAR_FOR_OPPSTART',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'INKLUDERINGSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const KlarForOppstartArena: Story = {
    name: 'Klar For Oppstart',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: klarForOppstartArena },
};

const gjennomføres: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'GJENNOMFØRES',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const Gjennomføres: Story = {
    name: 'Gjennomføres',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: gjennomføres },
};

const avsluttet: Avtale = {
    ...lonnstilskuddAvtaleMock,
    erUfordelt: false,
    status: 'AVSLUTTET',
    annullertTidspunkt: '2021-08-01',
    tiltakstype: 'MIDLERTIDIG_LONNSTILSKUDD',
    tilskuddPeriode: [
        {
            beløp: 23324,
            startDato: '2023-05-03',
            sluttDato: '2023-05-31',
            lonnstilskuddProsent: 60,
            id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
            godkjentAvNavIdent: undefined,
            godkjentTidspunkt: undefined,
            enhet: undefined,
            enhetsnavn: undefined,
            avslagsårsaker: new Set([]),
            avslagsforklaring: undefined,
            avslåttAvNavIdent: undefined,
            avslåttTidspunkt: undefined,
            løpenummer: 1,
            status: 'UBEHANDLET',
            refusjonStatus: undefined,
            aktiv: true,
            kanBesluttesFom: '-999999999-01-01',
            kanBehandles: true,
        },
    ],
    godkjentAvDeltaker: '2021-08-01',
    godkjentAvArbeidsgiver: '20-08-01',
    godkjentAvVeileder: '2021-08-01',
    gjeldendeTilskuddsperiode: {
        beløp: 23324,
        startDato: '2023-05-03',
        sluttDato: '2023-05-31',
        lonnstilskuddProsent: 60,
        id: '370b1f98-9431-4286-98ce-1cc61c824cb2',
        godkjentAvNavIdent: undefined,
        godkjentTidspunkt: undefined,
        enhet: undefined,
        enhetsnavn: undefined,
        avslagsårsaker: new Set([]),
        avslagsforklaring: undefined,
        avslåttAvNavIdent: undefined,
        avslåttTidspunkt: undefined,
        løpenummer: 1,
        status: 'UBEHANDLET',
        refusjonStatus: undefined,
        aktiv: true,
        kanBesluttesFom: '-999999999-01-01',
        kanBehandles: true,
    },
    avtaleInngått: '2021-08-01',
    annullertGrunn: 'annulert grunn',
    gjeldendeInnhold: {
        ...lonnstilskuddAvtaleMock.gjeldendeInnhold,
        startDato: '2021-08-01',
        sluttDato: '2021-08-01',
    },
};

export const Avsluttet: Story = {
    name: 'Avsluttet',
    parameters: {
        msw: {
            handlers: kreverAktsomhetHandler,
        },
    },
    args: { avtale: avsluttet },
};
