apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tiltaksgjennomforing-labs
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{image}}
    port: 3000
    vault:
        enabled: false
    ingresses:
        - 'https://tiltaksgjennomforing-labs.ekstern.dev.nav.no'
    liveness:
        path: /tiltaksgjennomforing/internal/isAlive
        initialDelay: 5
    readiness:
        path: /tiltaksgjennomforing/internal/isReady
        initialDelay: 5
    env:
        - name: MILJO
          value: dev-gcp-labs
        - name: API_URL
          value: 'http://tiltaksgjennomforing-api-labs'
        - name: LOGIN_URL
          value: '/tiltaksgjennomforing/fakelogin/aad'
        - name: LOGOUT_URL
          value: '/tiltaksgjennomforing/fakelogout?domain=ekstern.dev.nav.no'
        - name: ENABLE_EXTERNAL_MENU
          value: ''
        - name: DECORATOR_EXTERNAL_URL
          value: ''
        - name: ENABLE_INTERNAL_MENU
          value: ''
    accessPolicy:
      outbound:
        external:
          - host: tiltak-fakelogin.ekstern.dev.nav.no
        rules:
          - application: tiltaksgjennomforing-api-labs
          - application: tiltak-stillingstitler
