apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tiltaksgjennomforing-labs
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{image}}
    port: 3000
    vault:
        enabled: {{vault-enabled}}
    ingresses:
        - '{{{ingress}}}'
    liveness:
        path: /tiltaksgjennomforing/internal/isAlive
        initialDelay: 5
    readiness:
        path: /tiltaksgjennomforing/internal/isReady
        initialDelay: 5
    env:
        - name: MILJO
          value: dev-gcp-labs
        - name: APIGW_URL
          value: '{{{api-gw-url}}}'
        - name: ISSO_LOGIN_URL
          value: '{{{isso-login-url}}}'
        - name: SELVBETJENING_LOGIN_URL
          value: '{{{selvbetjening-login-url}}}'
        - name: LOGIN_URL
          value: '{{{login-url}}}'
        - name: LOGOUT_URL
          value: '{{{logout-url}}}'
        - name: ENABLE_EXTERNAL_MENU
          value: '{{{enable-external-menu}}}'
        - name: DECORATOR_EXTERNAL_URL
          value: '{{{decorator-external-url}}}'
        - name: ENABLE_INTERNAL_MENU
          value: '{{{enable-internal-menu}}}'
        - name: DECORATOR_INTERNAL_SCRIPT
          value: '{{{decorator-external-script}}}'
        - name: DECORATOR_INTERNAL_STYLING
          value: '{{{decorator-external-styling}}}'
        - name: ARBEIDSGIVER_DIALOG_URL
          value: {{{arbeidsgiver-dialog}}}
    {{#if labs}}
    accessPolicy:
      outbound:
        external:
          - host: tiltak-fakelogin.ekstern.dev.nav.no
        rules:
          - application: tiltaksgjennomforing-api-labs
          - application: tiltak-stillingstitler
    {{/if}}