apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tiltaksgjennomforing-storybook
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    port: 8080
    ingresses:
        - https://tiltaksgjennomforing-storybook.intern.dev.nav.no
    liveness:
        path: /isAlive
        initialDelay: 10
    readiness:
        path: /isReady
        initialDelay: 10
    replicas:
        min: 1
        max: 1
