"ingress": "https://tiltaksgjennomforing.intern.nav.no"
"miljo": "prod-gcp"
"api-gw-url": "https://tiltak-proxy.prod-fss-pub.nais.io"
"login-url": "/oauth2/login?redirect=/tiltaksgjennomforing"
"logout-url": "/oauth2/logout"
"stillingstitler-url": "http://tiltak-stillingstitler"
"tiltak-proxy-api-scope": "api://prod-fss.arbeidsgiver.tiltak-proxy/.default"
"modiacontextholder-api-scope": "api://prod-gcp.personoversikt.modiacontextholder/.default"
"proxy-cluster": "prod-fss"
"aad-redirect-url": "https://tiltaksgjennomforing.intern.nav.no/oauth2/callback"
"decorator-internal": "https://cdn.nav.no/personoversikt/internarbeidsflate-decorator-v3/prod/latest/dist"
"decorator-internal-script": "/internarbeidsflate-decorator-v3/prod/latest/dist/bundle.js"
"decorator-internal-styling": "/internarbeidsflate-decorator-v3/prod/latest/dist/index.css"
