"ingress": "https://arbeidsgiver.nav.no/tiltaksgjennomforing"
"api-gw-url": "https://tiltak-proxy.prod-fss-pub.nais.io"
"selvbetjening-login-url": "/tiltaksgjennomforing/oauth2/login"
"logout-url": "/tiltaksgjennomforing/oauth2/logout"
"stillingstitler-url": "http://tiltak-stillingstitler"
"api-audience": "prod-fss:arbeidsgiver:tiltak-proxy"
"proxy-cluster": "prod-fss"