"ingress": "https://arbeidsgiver.nav.no/tiltaksgjennomforing"
"api-gw-url": "https://tiltak-proxy.prod-fss-pub.nais.io"
"login-url": "/tiltaksgjennomforing/oauth2/login"
"logout-url": "/tiltaksgjennomforing/oauth2/logout"
"stillingstitler-url": "http://tiltak-stillingstitler"
"api-scope": "api://prod-fss.arbeidsgiver.tiltak-proxy/.default"
"proxy-cluster": "prod-fss"