name: Bygg branch

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    name: Bygg branch
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # ratchet:actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Server install
        working-directory: ./server
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Typescript
        run: npm run ts
      - name: Prettier
        run: npm run prettier
      - name: Kjør tester
        run: npm run test
