name: Bygg branch

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    name: Bygg branch
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Sett opp pnpm
        uses: pnpm/action-setup@v4
      - name: Konfigurer pnpm
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
      - name: Sett opp node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            server/pnpm-lock.yaml
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Server install
        working-directory: ./server
        run: pnpm install --frozen-lockfile
      - name: Typescript
        run: pnpm run ts
      - name: Prettier
        run: pnpm run prettier
      - name: Kjør tester
        run: pnpm run test
